name: hello world + date

on:
  issues:
    types:
      - opened
      - edited
      - closed
  pull_request:
    types:
      - ready_for_review
  gollum:
  schedule:
   - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: fedora-latest
    steps:
      - name: print hello world and date every month
        run: echo Hello, world! Today is {month}-{day}-{year} {hour}:{minute}:{second}
