name: version

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print latest ubuntu version
        run: lsb_release
  macOs:
    runs-on: macos-latest
    steps:
      - name: print latest macOs version
        run: sw_vers
  windows:
    runs-on: windows-latest
    steps:
      - name: print latest Windows version
        run: Get-ComputerInfo
