name: version

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print latest ubuntu version
        run: lsb_release
      - name: print latest macOs version
        run: sw_vers
      - name: print latest Windows version
        run: Get-ComputerInfo
